export{default as Navbar} from './Navbar'
export {default as Hero} from './Hero'
export {default as Highlight} from './Highlight'
export {default as Model} from './Model'
export {default as Features} from './Features'
export {default as HowItWorks} from './HowItWorks'